### ISSUE TITLE
Support for using different openai base url

### ISSUE THREAD

**Issue by VectorZhao** [bThink-BGU/LeafLLM#1]
Thank you very much for developing this project. Please consider adding support for the **base URL**, as shown in the image below.
![image](https://github.com/bThink-BGU/LeafLLM/assets/16644993/5a56dc36-c111-4ddb-99d9-f7ba3d9ef335)

**Comment by achiyae** [comment]
Thanks, this is definitely on my list.
I plan to give users the ability to edit all API hyperparameters.

**Comment by achiyae** [comment]
We've updated the API path to chat/completion in release 1.3.0. 
Since OpenAI deprecated all other path, this issue is no longer relevant.

**Comment by VectorZhao** [comment]
I think you misunderstood my meaning, just like openaitranslator, which allows users to input their own API BASE URL and choose which model to use.

**Comment by VectorZhao** [comment]
![image](https://github.com/bThink-BGU/LeafLLM/assets/16644993/02d8caf1-aec6-4049-a1e6-f769b2780420)
In the latest version, we can still only fill in the token.

**Comment by achiyae** [comment]
Okay, I understand, reopening...

**Comment by achiyae** [comment]
Version 1.4.0 will support it, currently by editing a json

**Comment by VectorZhao** [comment]
> Version 1.4.0 will support it, currently by editing a json

It can indeed be customized now, which is great. Thank you very much.

**Comment by achiyae** [comment]
Great!

I would appreciate it if you could star the project in GitHub and also provide feedback in the store https://chrome.google.com/webstore/detail/leafllm/feomoidgfifpofabcapiipjjjoigjeoa

Achiya
