### ISSUE TITLE
bug Failed to execute the 'Complete' command. Error message: undefined

### ISSUE THREAD

**Issue by pengzhangzhi** [bThink-BGU/LeafLLM#5]
I manually set the keybinding, it does not work. 
Below is the setting. I have put in my API key.
```

LeafLLM

Activate the extension
Ctrl + G


In Edge
Use the selected text to ask GPT. It adds to the beginning of the selected text: 'In Latex, '
Type a shortcut

In Edge
Complete selected text
Ctrl + O


Global
Improve selected text
Ctrl + I


Global
```

**Comment by achiyae** [comment]
Thank you for reporting.
I have fixed the bug and sent it to production, though it might take time for Google to publish it.
The new version is 1.2.2. Watch the [extension page](https://chromewebstore.google.com/detail/leafllm/feomoidgfifpofabcapiipjjjoigjeoa) for updates.

Once the extension is updated, you must reenable the different commands.

Let me know if it worked. Once it does, I would appreciate it if you could [star the extension](https://chromewebstore.google.com/detail/leafllm/feomoidgfifpofabcapiipjjjoigjeoa)...

**Comment by achiyae** [comment]
I'm closing the issue for now. If there's still a bug - please reopen
