### ISSUE TITLE
Invalid API key error

### ISSUE THREAD

**Issue by HarshBabla99** [bThink-BGU/LeafLLM#9]
Hi, 
I can't get the extension to accept any of my OpenAI API keys. I tried to use personal and project API keys. 
Could you please take a look? Thanks.

**Comment by achiyae** [comment]
What is the error that you get? How do you know that it didn't take the key?
You should see this (saying "API Token is set"):
![image](https://github.com/user-attachments/assets/9cd06524-dfad-48b6-85ab-30fc17c464c7)

**Comment by HarshBabla99** [comment]
I get the following error: 

<img width="484" alt="image" src="https://github.com/user-attachments/assets/f9eca01c-04be-4216-ba3e-64aba9b59a73">

I used the same API key on other platforms, and it worked just fine.

**Comment by achiyae** [comment]
I think I know why. You are using Project keys and not the old user keys. I will add support for that today; stay tuned...

**Comment by achiyae** [comment]
I pushed a new version, it will probably take a few hours. The new version is 1.4.1.
You are welcome to reopen this issue if it does not solve your problem.

**Comment by HarshBabla99** [comment]
works now thanks!
